# fly.toml app configuration file generated for proud-frost-5505 on 2023-10-07T21:13:42+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "proud-frost-5505"
primary_region = "waw"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 0
  processes = ["app"]
